// Differential tests: replay scenarios generated by the Python reference registry
// (task_registry.py) against GuardRegistry and require identical results, including
// error messages and the canonical JSON of the whole durable state.
import Foundation
import XCTest
import GuardCore
@testable import GuardRegistry

private let signers: [String: Signer] = [
    "S": try! Signer(teamID: "TEAM000001", signingID: "dev.agentbelt.supervisor"),
    "A": try! Signer(teamID: "TEAM000001", signingID: "dev.agentbelt.approver"),
    "O": try! Signer(teamID: "TEAM000002", signingID: "com.example.other"),
]

/// Runs the generator with the system Python. The generated file is not committed:
/// the generator is the source of truth and always matches the checked-out Python model.
func generateVectors(scenarios: Int, steps: Int, seed: Int) throws -> JSONValue {
    let script = URL(fileURLWithPath: #filePath).deletingLastPathComponent().appendingPathComponent("generate_vectors.py")
    let output = FileManager.default.temporaryDirectory.appendingPathComponent("agentbelt-vectors-\(UUID().uuidString).json")
    defer { try? FileManager.default.removeItem(at: output) }
    let python = Process()
    python.executableURL = URL(fileURLWithPath: "/usr/bin/python3")
    python.arguments = ["-I", script.path, "--out", output.path, "--scenarios", String(scenarios),
                        "--steps", String(steps), "--seed", String(seed)]
    try python.run()
    python.waitUntilExit()
    guard python.terminationStatus == 0 else { throw JSONError(reason: "vector generator failed") }
    return try StrictJSON.parse(try Data(contentsOf: output))
}

private extension JSONValue {
    subscript(key: String) -> JSONValue { objectValue?[key] ?? .null }
    subscript(index: Int) -> JSONValue { arrayValue.map { index < $0.count ? $0[index] : .null } ?? .null }
    var int64: Int64 { intValue! }
    var string: String { stringValue! }
}

private func identity(_ value: JSONValue) -> ProcessIdentity? {
    guard let items = value.arrayValue else { return nil }
    return try! ProcessIdentity(pid: Int32(items[0].int64), pidVersion: Int32(items[1].string)!)
}

private func peer(_ value: JSONValue) -> Peer {
    Peer(process: identity(value[0])!, signer: signers[value[1].string]!)
}

private func image(_ value: JSONValue) -> ExecutableImage? {
    guard let items = value.arrayValue else { return nil }
    return try! ExecutableImage(path: items[0].string, digest: items[1].string)
}

private func outcomeJSON(_ outcome: Outcome) -> JSONValue {
    .object(["route": .string(outcome.route), "allowed": .bool(outcome.allowed), "reason": .string(outcome.reason),
             "task_id": outcome.taskID.map { .string($0) } ?? .null, "revision": outcome.revision.map { .int($0) } ?? .null])
}

private func control(_ body: () throws -> JSONValue) -> JSONValue {
    do {
        return .object(["ok": try body()])
    } catch let error as RegistryError {
        return .object(["error": .string(error.reason)])
    } catch {
        return .object(["unexpected": .string(String(describing: error))])
    }
}

private struct SyntheticStoreFailure: Error {}

/// The durable store of a scenario: the last document it accepted, and whether it fails.
final class SyntheticStore {
    var saved: String?
    var failing = false

    func persist(_ document: JSONValue) throws {
        if failing { throw SyntheticStoreFailure() }
        saved = CanonicalJSON.encode(document)
    }
}

/// Mirrors generate_vectors.apply_corruption.
private func corrupted(_ document: JSONValue, _ corruption: JSONValue) -> JSONValue {
    guard case var .object(fields) = document else { return document }
    switch corruption["kind"].string {
    case "version":
        fields["version"] = corruption["value"]
    case "drop_tickets":
        fields["tickets"] = nil
    case "ticket_duplicate":
        var tickets = fields["tickets"]!.arrayValue!
        tickets.append(tickets[0])
        fields["tickets"] = .array(tickets)
    default:
        var tickets = fields["tickets"]!.arrayValue!
        guard case var .object(ticket) = tickets[0] else { return document }
        ticket[corruption["field"].string] = corruption["value"]
        tickets[0] = .object(ticket)
        fields["tickets"] = .array(tickets)
    }
    return .object(fields)
}

final class Replayer {
    var registry: Registry
    let config: RegistryConfig
    let store = SyntheticStore()

    init(configuration: JSONValue) throws {
        config = try RegistryConfig(supervisors: [signers["S"]!], approvers: [signers["A"]!],
                                    ticketTTLNs: configuration["ticket_ttl_ns"].int64,
                                    maxPendingRequests: Int(configuration["max_pending_requests"].int64),
                                    maxRecords: Int(configuration["max_records"].int64))
        registry = try Registry(config: config, bootID: "boot-1", nowNs: 100, persist: store.persist)
    }

    private func restore(from text: String, _ args: JSONValue) -> JSONValue {
        control {
            let document = try StrictJSON.parse(Data(text.utf8))
            registry = try Registry.restore(document, config: config, bootID: args["boot_id"].string,
                                            nowNs: args["now"].intValue ?? 0, persist: store.persist)
            return .null
        }
    }

    /// Executes one step and returns the value to compare with the Python expectation.
    func run(_ step: JSONValue) -> JSONValue {
        let args = step["args"]
        let now = args["now"].intValue ?? 0
        switch step["op"].string {
        case "propose":
            return control {
                let contract = try ContractCodec.decode(args["contract"])
                return .string(try registry.propose(peer(args["peer"]), contract: contract,
                                                    parentTaskID: args["parent"].stringValue, nowNs: now))
            }
        case "confirm":
            return control { try registry.confirm(peer(args["peer"]), digest: args["digest"].string, nowNs: now); return .null }
        case "reject_proposal":
            return control { try registry.rejectProposal(peer(args["peer"]), digest: args["digest"].string, nowNs: now); return .null }
        case "revoke":
            return control { try registry.revoke(peer(args["peer"]), taskID: args["task"].string, nowNs: now); return .null }
        case "register_launch":
            return control {
                try registry.registerLaunch(peer(args["peer"]), taskID: args["task"].string, image: image(args["image"])!,
                                            child: identity(args["child"])!, nowNs: now)
                return .null
            }
        case "ticket_status":
            return control { .string(try registry.ticketStatus(peer(args["peer"]), child: identity(args["child"])!, nowNs: now)) }
        case "pending_requests":
            return control {
                .array(try registry.pendingRequests(peer(args["peer"])).map { request in
                    .object(["request_id": .string(request.requestID), "task_id": .string(request.taskID),
                             "revision": .int(request.revision), "path": .string(request.path),
                             "operations": .array(request.operations.map(\.rawValue).sorted().map { .string($0) })])
                })
            }
        case "pending_proposals":
            return control {
                .array(try registry.pendingProposals(peer(args["peer"])).map { view in
                    .object(["digest": .string(view.digest), "contract": view.contract.jsonValue,
                             "parent_task_id": view.parentTaskID.map { .string($0) } ?? .null,
                             "proposer": identityJSON(view.proposer)])
                })
            }
        case "approve_request":
            return control {
                try registry.approveRequest(peer(args["peer"]), requestID: args["request"].string,
                                            expiresAtNs: args["expires"].int64, nowNs: now)
                return .null
            }
        case "reject_request":
            return control { try registry.rejectRequest(peer(args["peer"]), requestID: args["request"].string, nowNs: now); return .null }
        case "fork":
            registry.onFork(parent: identity(args["parent"]), child: identity(args["child"]), nowNs: now)
            return .null
        case "exit":
            registry.onExit(process: identity(args["process"]), nowNs: now)
            return .null
        case "exec":
            return outcomeJSON(registry.onExec(process: identity(args["process"]), parent: identity(args["parent"]),
                                               target: identity(args["target"]), image: image(args["image"]),
                                               script: args["script"].stringValue, nowNs: now))
        case "file":
            let operations = Set(args["operations"].arrayValue!.map(\.string))
            let subtree: Bool
            if case let .bool(flag) = args["subtree"] { subtree = flag } else { subtree = false }
            return outcomeJSON(registry.authorizeFile(process: identity(args["process"]), parent: identity(args["parent"]),
                                                      path: args["path"].string, operations: operations,
                                                      subtree: subtree, nowNs: now))
        case "process":
            return outcomeJSON(registry.authorizeProcess(process: identity(args["process"]), parent: identity(args["parent"]),
                                                         target: identity(args["target"]),
                                                         operation: args["operation"].string, nowNs: now))
        case "snapshot":
            return .string(CanonicalJSON.encode(registry.toDocument()))
        case "restore":
            return restore(from: CanonicalJSON.encode(registry.toDocument()), args)
        case "crash_restore":
            return restore(from: store.saved!, args)
        case "store_mode":
            if case let .bool(failing) = args["failing"] { store.failing = failing }
            return .null
        case "checkpoint":
            return control { try registry.checkpoint(); return .null }
        case "corrupt_restore":
            return control {
                let document = try StrictJSON.parse(Data(CanonicalJSON.encode(registry.toDocument()).utf8))
                _ = try Registry.restore(corrupted(document, args["corruption"]), config: config,
                                         bootID: args["boot_id"].string, nowNs: now)
                return .null
            }
        case "saved":
            return store.saved.map { .string($0) } ?? .null
        default:
            return .string("unknown op")
        }
    }
}

final class DifferentialTests: XCTestCase {
    func testSwiftRegistryMatchesPythonReferenceOnGeneratedScenarios() throws {
        // AGENTBELT_DIFF_SCENARIOS / AGENTBELT_DIFF_SEED widen a one-off run; CI uses the defaults.
        let environment = ProcessInfo.processInfo.environment
        let scenarios = environment["AGENTBELT_DIFF_SCENARIOS"].flatMap(Int.init) ?? 120
        let seed = environment["AGENTBELT_DIFF_SEED"].flatMap(Int.init) ?? 0
        let vectors = try generateVectors(scenarios: scenarios, steps: 160, seed: seed)
        var compared = 0
        for scenario in vectors["scenarios"].arrayValue! {
            let replayer = try Replayer(configuration: scenario["config"])
            for (index, step) in scenario["steps"].arrayValue!.enumerated() {
                let actual = replayer.run(step)
                compared += 1
                if actual != step["expect"] {
                    XCTFail("""
                        seed \(scenario["seed"].int64) step \(index) op \(step["op"].string)
                        expected \(CanonicalJSON.encode(step["expect"]))
                        actual   \(CanonicalJSON.encode(actual))
                        """)
                    break  // later steps diverge once state differs
                }
            }
        }
        XCTAssertGreaterThan(compared, scenarios * 100)
    }

    func testAttenuationMatchesPythonOnGeneratedPairs() throws {
        let vectors = try generateVectors(scenarios: 0, steps: 0, seed: 11)
        var positives = 0
        for pair in vectors["attenuation"].arrayValue! {
            let parent = try ContractCodec.decode(pair["parent"])
            let child = try ContractCodec.decode(pair["child"])
            guard case let .bool(expected) = pair["attenuation"] else { return XCTFail("missing verdict") }
            positives += expected ? 1 : 0
            XCTAssertEqual(isAttenuation(parent: parent, child: child), expected,
                           "parent \(CanonicalJSON.encode(pair["parent"])) child \(CanonicalJSON.encode(pair["child"]))")
        }
        XCTAssertGreaterThan(positives, 20)  // the corpus must exercise accepted pairs too
    }

    func testContractLoaderMatchesPythonAcceptanceAndMessages() throws {
        let vectors = try generateVectors(scenarios: 0, steps: 0, seed: 7)
        for entry in vectors["contracts"].arrayValue! {
            let text = entry["text"].string
            let actual: JSONValue
            do {
                let contract = try TaskContract.load(json: Data(text.utf8))
                actual = .object(["ok": .string(CanonicalJSON.encode(contract.jsonValue))])
            } catch let error as PolicyError {
                actual = .object(["error": .string(error.reason)])
            }
            var expected = entry.objectValue!
            expected["text"] = nil
            if text.contains("\\ud800"), expected["error"] != nil {
                // Known, deliberate difference: Python decodes a lone surrogate and rejects it
                // later; Swift cannot represent it and rejects at the JSON layer. Both reject.
                XCTAssertEqual(actual, .object(["error": .string("invalid contract JSON")]))
                continue
            }
            XCTAssertEqual(actual, .object(expected), "contract text: \(text.prefix(120))")
        }
    }
}
